source 'https://rubygems.org'
ruby '2.2.2'

gem 'rails', '4.2.3'
gem 'bourbon', '~> 4.2.3'
gem 'cancancan', '~> 1.12.0'
gem 'carrierwave', '~> 0.10.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise', '~> 3.5.1'
gem 'devise-i18n', '~> 0.12.1'
gem 'devise-i18n-views', '~> 0.3.4'
gem 'devise_invitable', '~> 1.4.2'
gem 'dynamic_sitemaps', '~> 2.0.0'
gem 'figaro', '~> 1.1.1'
gem 'fog', '~> 1.31.0'
gem 'font-awesome-sass', '~> 4.3.2.1'
gem 'friendly_id', '~> 5.1.0'
gem 'simple_calendar', '~> 1.1.10'
gem 'gravatarify', '~> 3.1.1'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'kaminari', '~> 0.16.3'
gem 'meta-tags', '~> 2.0.0'
gem 'neat', '~> 1.7.2'
gem 'omniauth', '~> 1.2.2'
gem 'omniauth-facebook', '~> 2.0.0'
gem 'omniauth-linkedin-oauth2', '~> 0.1.5'
gem 'omniauth-twitter', '~> 1.1.0'
gem 'pg', '~> 0.18.2'
gem 'puma', '~> 2.11.3'
gem 'rack-google-analytics', '~> 1.2.0'
gem 'rails-i18n', '~> 4.0.4'
gem 'rails_admin', '~> 0.6.8'
gem 'rails_admin-i18n', github: 'igmarin/rails_admin-i18n'
gem 'ransack', '~> 1.6.6'
gem 'rolify', '~> 4.0.0'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'bullet'
  gem 'letter_opener'
end

gem 'rails_12factor', group: :production
