source 'https://rubygems.org'
ruby '2.2.2'

gem 'rails', '4.2.3'
gem 'bourbon'
gem 'cancancan'
gem 'carrierwave'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'devise-i18n'
gem 'devise-i18n-views'
gem 'devise_invitable', '~> 1.4.1'
gem 'dynamic_sitemaps'
gem 'figaro'
gem 'figaro'
gem 'fog'
gem 'font-awesome-sass'
gem 'friendly_id'
gem 'fullcalendar-rails'
gem 'gravatarify'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'kaminari'
gem 'meta-tags'
gem 'neat'
gem 'omniauth', '~> 1.2.2'
gem 'omniauth-facebook', '~> 2.0.0'
gem 'omniauth-linkedin-oauth2', '~> 0.1.5'
gem 'omniauth-twitter', '~> 1.1.0'
gem 'pg'
gem 'puma'
gem 'rack-google-analytics', '~> 1.2.0'
gem 'rails-i18n'
gem 'rails_admin'
gem 'rails_admin-i18n', github: 'igmarin/rails_admin-i18n'
gem 'ransack'
gem 'rolify'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'wysiwyg-rails', github: 'igmarin/wysiwyg-rails'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'bullet'
  gem 'letter_opener'
end

gem 'rails_12factor', group: :production
